const theme = {
  colors: {
    primary: '#00664F',
    secondary: '#13997B',
    third: '#BAEDD4',
    forth: '#E0FCEF',
    background: '#F7F6F3',
    warning: '#FF4D4D',
    white: '#FFF',
    gray100: '#F5F5F5',
    gray300: '#D9D9D9',
    gray500: '#999',
    black: '#222',
  },
  fonts: {
    body: `'Pretendard Variable', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif`,
    title: `'Oleo Script Swash Caps', cursive`,
  },
  display: {
    logo: {
      fontFamily: `'Oleo Script Swash Caps', cursive`,
      fontSize: '2rem',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: 'normal',
    },
    large: {
      fontFamily: `'Pretendard Variable'`,
      fontSize: '1.5rem',
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: '140%',
    },
    medium: {
      fontFamily: `'Pretendard Variable'`,
      fontSize: '1.25rem',
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: 'normal',
    },
    small: {
      fontFamily: `'Pretendard Variable'`,
      fontSize: '0.875rem',
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: 'normal',
    },
    title: {
      large: {
        fontFamily: `'Pretendard Variable'`,
        fontSize: '1.25rem',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: '140%',
      },
      medium: {
        fontFamily: `'Pretendard Variable'`,
        fontSize: '1rem',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: 'normal',
      },
      small: {
        fontFamily: `'Pretendard Variable'`,
        fontSize: '0.75rem',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 'normal',
      },
      extraSmall: {
        fontFamily: `'Pretendard Variable'`,
        fontSize: '0.625rem',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 'normal',
      },
    },
    body: {
      large: {
        fontFamily: `'Pretendard Variable'`,
        fontSize: '1rem',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: '140%',
      },
      medium: {
        fontFamily: `'Pretendard Variable'`,
        fontSize: '0.875rem',
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: '150%',
      },
      small: {
        fontFamily: `'Pretendard Variable'`,
        fontSize: '0.75rem',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: '150%',
      },
    },
    caption: {
      large: {
        fontFamily: `'Pretendard Variable'`,
        fontSize: '0.75rem',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: '140%',
      },
      medium: {
        fontFamily: `'Pretendard Variable'`,
        fontSize: '0.625rem',
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: 'normal',
      },
      small: {
        fontFamily: `'Pretendard Variable'`,
        fontSize: '0.5625rem',
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 'normal',
      },
    },
  },
};

export default theme;
