const USERS = [
  {
    id:"1",
    profileimageurl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqyxfxX8QSTvO1ULBKz6IK_KKsMFoiOr9LxoMYKTdAkbIpHxHC",
    nickname: "닉네임",
    studentid: "23",
    major: "인공지능데이터사이언스학부",
    talent: "Spring, Java, JS",
    location: "서울 관악구 봉천동",
    재능기부: true,
    재능교환: true,
    커피챗: true,
  },
  {
    id:"2",
    profileimageurl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqyxfxX8QSTvO1ULBKz6IK_KKsMFoiOr9LxoMYKTdAkbIpHxHC",
    nickname: "닉네임",
    studentid: "23",
    major: "컴퓨터공학과",
    talent: "Spring, Java, JS",
    location: "서울 관악구 봉천동",
    재능기부: true,
    재능교환: true,
    커피챗: true,
  },
  {
    id:"3",
    profileimageurl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqyxfxX8QSTvO1ULBKz6IK_KKsMFoiOr9LxoMYKTdAkbIpHxHC",
    nickname: "닉네임",
    studentid: "23",
    major: "컴퓨터공학과",
    talent: "Spring, Java, JS",
    location: "서울 관악구 봉천동",
    재능기부: true,
    재능교환: true,
    커피챗: true,
  },
  {
    id:"4",
    profileimageurl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqyxfxX8QSTvO1ULBKz6IK_KKsMFoiOr9LxoMYKTdAkbIpHxHC",
    nickname: "닉네임",
    studentid: "23",
    major: "컴퓨터공학과",
    talent: "Spring, Java, JS",
    location: "서울 관악구 봉천동",
    재능기부: true,
    재능교환: true,
    커피챗: true,
  },
  {
    id:"5",
    profileimageurl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqyxfxX8QSTvO1ULBKz6IK_KKsMFoiOr9LxoMYKTdAkbIpHxHC",
    nickname: "닉네임",
    studentid: "23",
    major: "컴퓨터공학과",
    talent: "Spring, Java, JS",
    location: "서울 관악구 봉천동",
    재능기부: true,
    재능교환: true,
    커피챗: true,
  },
  {
    id:"6",
    profileimageurl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqyxfxX8QSTvO1ULBKz6IK_KKsMFoiOr9LxoMYKTdAkbIpHxHC",
    nickname: "닉네임",
    studentid: "23",
    major: "컴퓨터공학과",
    talent: "Spring, Java, JS",
    location: "서울 관악구 봉천동",
    재능기부: true,
    재능교환: true,
    커피챗: true,
  },
  {
    id:"7",
    profileimageurl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqyxfxX8QSTvO1ULBKz6IK_KKsMFoiOr9LxoMYKTdAkbIpHxHC",
    nickname: "닉네임",
    studentid: "23",
    major: "컴퓨터공학과",
    talent: "Spring, Java, JS",
    location: "서울 관악구 봉천동",
    재능기부: true,
    재능교환: true,
    커피챗: true,
  },
  {
    id:"8",
    profileimageurl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqyxfxX8QSTvO1ULBKz6IK_KKsMFoiOr9LxoMYKTdAkbIpHxHC",
    nickname: "닉네임",
    studentid: "23",
    major: "컴퓨터공학과",
    talent: "Spring, Java, JS",
    location: "서울 관악구 봉천동",
    재능기부: true,
    재능교환: true,
    커피챗: true,
  },
  {
    id:"9",
    profileimageurl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqyxfxX8QSTvO1ULBKz6IK_KKsMFoiOr9LxoMYKTdAkbIpHxHC",
    nickname: "닉네임",
    studentid: "23",
    major: "컴퓨터공학과",
    talent: "Spring, Java, JS",
    location: "서울 관악구 봉천동",
    재능기부: false,
    재능교환: true,
    커피챗: false,
  },
  {
    id:"10",
    profileimageurl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqyxfxX8QSTvO1ULBKz6IK_KKsMFoiOr9LxoMYKTdAkbIpHxHC",
    nickname: "닉네임",
    studentid: "23",
    major: "컴퓨터공학과",
    talent: "Spring, Java, JS",
    location: "서울 관악구 봉천동",
    재능기부: false,
    재능교환: true,
    커피챗: true,
  },
  {
    id:"11",
    profileimageurl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqyxfxX8QSTvO1ULBKz6IK_KKsMFoiOr9LxoMYKTdAkbIpHxHC",
    nickname: "닉네임",
    studentid: "23",
    major: "컴퓨터공학과",
    talent: "Spring, Java, JS",
    location: "서울 관악구 봉천동",
    재능기부: true,
    재능교환: true,
    커피챗: true,
  },
  {
    id:"12",
    profileimageurl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqyxfxX8QSTvO1ULBKz6IK_KKsMFoiOr9LxoMYKTdAkbIpHxHC",
    nickname: "닉네임",
    studentid: "23",
    major: "컴퓨터공학과",
    talent: "Spring, Java, JS",
    location: "서울 관악구 봉천동",
    재능기부: true,
    재능교환: false,
    커피챗: false,
  },
  {
    id:"13",
    profileimageurl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqyxfxX8QSTvO1ULBKz6IK_KKsMFoiOr9LxoMYKTdAkbIpHxHC",
    nickname: "닉네임",
    studentid: "23",
    major: "컴퓨터공학과",
    talent: "Spring, Java, JS",
    location: "서울 관악구 봉천동",
    재능기부: true,
    재능교환: false,
    커피챗: true,
  },
];

export default USERS;